[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "data/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/taskup"
  status = 200
